### ISSUE TITLE
replace _.cloneDeep for snapshots with more performant default

### ISSUE THREAD

**Issue by mateodelnorte** [mateodelnorte/sourced#11]
https://github.com/mateodelnorte/sourced/blob/master/lib/entity.js#L110 _.cloneDeep is far too slow when entities get large or have special typed properties such as Map and Set. 

best option is probably to replace with `JSON.parse(JSON.stringify(this));`, and continue to allow overriding `prototype.snapshot` when implementers need to do something custom. 

this will be a breaking change.

**Comment by rkaw92** [comment]
One idea that I use is to not provide a default snapshot get nor snapshot apply function at all. My Event Sourcing / DDD framework `esdf` requires the programmer to implement this themselves, or else it does not snapshot (also splits the snapshotting functionality off, so you can run without a snapshotting layer). One advantage that it provides is, when you're using ValueObjects extensively (as I am), it forces you to always think about restoring proper types. Of course, it takes some work and testing for each and every Aggregate Root to be snapshotted.

**Comment by mateodelnorte** [comment]
I basically decided this wasn't an issue. The default snapshotting uses _.cloneDeep, and works in nearly all scenarios. Model creators can always override the inherited behavior when in need of better performance, like: 
```

MyModel.prototype.snapshot = function snapshot () {
  return {
    id: this.id,
    childObject: this.childObject.toJson(),
    snapshotVersion: this.version,
    timestamp: this.timestamp,
    version: this.version
  };
};
``

**Comment by rkaw92** [comment]
Always glad to give it a prod.
