### ISSUE TITLE
How events work with a Service Bus.

### ISSUE THREAD

**Issue by eddieajau** [mateodelnorte/sourced#14]
Hi @mateodelnorte 

I'm just wondering how Entity events work with a service bus? Currently I'm doing something like this for a `File` entity:

```typescript
	serviceBus.listen('do.file.create', { ack: true }, (event: any) => {
		// TODO what happens if file already exists?
		let fileEntity = new FileEntity();

		fileEntity.create(event);

		fileRepository.commit(fileEntity, (err: Error) => {
			if (err) {
				return event.handle.reject(err);
			}

			event.handle.ack();
			serviceBus.send('on.file.created', event);
		});
	});
```

I'm not having the `create` method emit anything at this stage. Is this a reasonable approach?

Secondly, what happens if the Entity method is async, either taking a callback or returning a Promise? For example, I'm starting to build a `transform` method which resizes the file (in the case of an image) to maximum dimensions. It's possible that method could error, and I'd ordinarily have a method like that return a promise.

Thanks in advance.

**Comment by mateodelnorte** [comment]
Hi @eddieajau. What you've got is a reasonable approach, however, I usually have handlers that look like the following: 

```
/*jslint node: true */
'use strict';

const bus = require('../bus');
const FileEntity = require('../models/fileEntity');
const fileEntityRepository = require('../fileEntityRepository');
const log = require('llog');

module.exports.ack = true;

module.exports.routingKey = 'do.file.created';

module.exports.subscribe = module.exports.handler = (event, cb) => {

  fileEntityRepository.get(event.data.userId, (err, fileEntity) => {
    if (err) return cb(err);

    if ( ! fileEntity) {

      fileEntity = new FileEntity();

      fileEntity.initialize({
        id: event.data.id
      });

    } else {
      fileEntityRepository.unlock(fileEntity);
      log.warn(`fileEntity ${event.data.id} cannot be created. it already exists`);
      return cb();
    }

    fileEntity.once('created', (t) => {
      bus.publish('fileEntity.created', t, { correlationId: bus.correlationId() }, cb);
    });

    fileEntityRepository.commit(fileEntity, function (err) {
      if (err) return cb(err);

      fileEntity.removeAllListeners();

    });

  });

};
```
The extra structure I have above is for use with https://github.com/mateodelnorte/servicebus-register-handlers, which is a module that provides some project structure for your event handlers. I'm also using https://github.com/mateodelnorte/sourced-queued-repo to handle concurrency issues on entities, by locking entities when they're being operated on (hence the call to       `fileEntityRepository.unlock(fileEntity);`). 

I generally avoid asynchronous methods on Entities. I would, instead, call an asynch method in a handler and pass the result of that call as a parameter on an Entity method. This keeps the functionality of the Entity much simpler and avoids strange things from happening during apply and digest.

**Comment by eddieajau** [comment]
Thanks Matt. That's extremely helpful advice. One question (well, I have a few others but they can wait): is the `.initialize` method significant or is that just a convention you use?

**Comment by mateodelnorte** [comment]
It's a convention I use so that you can easily identify the first event in
an entity's audit trail.

**Comment by mateodelnorte** [comment]
Closing. Feel free to continue the conversation.
