### ISSUE TITLE
How to handle Entity meta?

### ISSUE THREAD

**Issue by eddieajau** [mateodelnorte/sourced#18]
Hi Matt. How do you normally handle entity meta like created date, last updated date, created by (user id), updated by etc?

**Comment by mateodelnorte** [comment]
These are just fields updated by digest methods. I typically would do something like: 
```
Customer.prototype._updatedBy = function (param) {
  this.updatedBy = param.updatedBy;
  this.updatedAt = param.updatedAt;
}
Entity.digestMethod(Customer, function create (param) {

  this.createdAt = moment.utc(new Date());
  /// + any additional props you need to set
  this._updatedBy(param);

  this.enqueue('created', this.toJson());

  return this;

});
Entity.digestMethod(Customer, function move (param) {

  this.address = param.address;
  /// + any additional props you need to set
  this._updatedBy(param);

  this.enqueue('moved', this.toJson());

  return this;

});
```
It's up to you if you want to enqueue an event in the _updatedBy function as well.

**Comment by eddieajau** [comment]
Ok, thanks. That's what I thought. I wondered about inferring the dates from the `timestamp` field in the Mongo record but I think that get's a little too tricky.

**Comment by eddieajau** [comment]
Matt, just out of interest, is `this.toJson()` something you implement by hand in your derived Entity?

**Comment by mateodelnorte** [comment]
Yup. Just a pattern I follow at times. You could just add easily emit an
object describing the change that happened, just the new value, or a before
and after.

**Comment by eddieajau** [comment]
Hrm, in your example you have `this.createdAt = moment.utc(new Date());` but that won't really work when events are replayed (it will always set the current date). That will have to be passed in as a parameter won't it?

**Comment by mateodelnorte** [comment]
Yeah, that actually occurred to me after I sent it. You actually want to
instantiate that date and pass it in from the handler.

**Comment by eddieajau** [comment]
Got it. Thanks!

**Comment by eddieajau** [comment]
I guess you can also technically include more data in `param` (see `Entity.digestMethod(Customer, function create (param) {`) than is technically supported. So if I wanted to weed out junk fields I'd have to do that manually as well (either in the Entity or in a wrapper service)?

**Comment by mateodelnorte** [comment]
I typically do make a memento object for the incoming param, like
(pseudo-code. I'd probably check to ensure the order didn't already exist
and perhaps do some other stuff here):
```
const Order = require('./models/order');
const repo = require('../orderRepository');

module.exports.routingKey = 'order.create';
module.exports.listen = function (param, cb) {
  var order = new Order();
  order.initialize({
    id: param.order.id,
    createdAt: param.order.createdAt,
    items: param.order.items,
  });
  repo.commit(order, cb);
};
```

If you don't want to do a memento, you might have an easier time with
updating paths through your system as doing something like
```
order.initialize(param.order);
```
will cause all of the order object's properties to be digested on the
event. But - you'll want to make sure you only pass exactly what the
service requires on the incoming command or event. For commands, this is
generally fine - there's often only one recipient service listening for
commands. For events, it's tough because any number of services may
subscribe.
