### ISSUE TITLE
Entity constructor arity during deserialization

### ISSUE THREAD

**Issue by alistairstead** [mateodelnorte/sourced#5]
If you have an Entity that has not handled 10 or more events before committing it will not be automatically snapshot with sourced-repos-mongo. When that entity is retrieved from the repository and deserialised no snapshots will be available.

```
function Entity (/*snapshot, evnts*/) {
  this.eventsToEmit = [];
  this.newEvents = []; 
  this.replaying = false;
  this.snapshotVersion = 0;
  this.timestamp = Date.now();
  this.version = 0;
  events.EventEmitter.call(this);
  var args = Array.prototype.slice.call(arguments);
  if (args[0]){
    var snapshot = args[0];
    this.merge(snapshot);  
  }
  if (args[1]){
    var evnts = args[1];
    this.replay(evnts);
  }
}
```

As a result the entity will be created using `merge()` rather than `replay()` but it will only be called with the first event in the stream.

The arity of the `Entity()` method should be checked to define with method should be used against the argument.

**Comment by mateodelnorte** [comment]
So, you want to be able to rehydrate an entity by just saying the following?
```
new Entity(events);
```
Currently, sourced-repo-mongo should use the following code to rehydrate entities: https://github.com/mateodelnorte/sourced-repo-mongo/blob/master/index.js#L209. If there were no snapshots, the value for snapshot will be null, and thus falsy. So merge gets skipped but replay gets called with the events.

**Comment by alistairstead** [comment]
I'm not seeing that happen but I will run some more testing.

**Comment by alistairstead** [comment]
Following an upgrade and updating the Entity implementation everything is now working as it should. Sorry for raising a defect for a PEBKAC issue.

**Comment by mateodelnorte** [comment]
No worries at all. Sounds like a documentation issue. ;)

**Comment by mateodelnorte** [comment]
btw, grab the latest version (0.3.0) of sourced-repo-mongo for an additional little enhancement - overriding snapshotFrequency.
